# -*- coding: utf-8 -*-
"""
Köprü — OmniRoute-style Provider Catalog
Kapsamlı provider kataloğu: 50+ sağlayıcı, servis türleri,
ücretsiz plan bilgileri ve UI metadata.
"""

from typing import Dict, List, Optional


# ── Provider Catalog ────────────────────────────────────────────────────────
# Her provider dict:
#   id        : str   — benzersiz tanımlayıcı (JSON key ile aynı)
#   alias     : str   — kısa rumuz / display-name
#   name      : str   — tam görünür ad (Türkçe-dostu)
#   icon      : str   — Material Icons adı
#   color     : str   — hex renk kodu (#RRGGBB)
#   textIcon  : str   — 2-4 karakter rozet metni
#   website   : str   — resmi URL
#   hasFree   : bool  — ücretsiz plan mevcut mu?
#   freeNote  : str   — ücretsiz plan notu (Türkçe)
#   serviceKinds : List[str] — sunulan servis türleri
#                         (chat, completion, embedding, image, audio,
#                          video, code, search, embedding, rerank, tts, stt)

PROVIDER_CATALOG: Dict[str, Dict] = {
    # ════════════════════════════════════════════════════════════════════════
    #  ÖN ÇİZGİ SAĞLAYICILAR  (Frontier)
    # ════════════════════════════════════════════════════════════════════════
    "openai": {
        "id": "openai",
        "alias": "OpenAI",
        "name": "OpenAI",
        "icon": "psychology",
        "color": "#10A37F",
        "textIcon": "AI",
        "website": "https://openai.com",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok; deneme kredisi mevcut",
        "serviceKinds": ["chat", "completion", "embedding", "image", "audio", "video", "code"],
    },
    "anthropic": {
        "id": "anthropic",
        "alias": "Anthropic",
        "name": "Anthropic",
        "icon": "smart_toy",
        "color": "#D4A574",
        "textIcon": "AN",
        "website": "https://anthropic.com",
        "hasFree": False,
        "freeNote": "API deneme kredisi mevcut",
        "serviceKinds": ["chat", "completion", "code"],
    },
    "google": {
        "id": "google",
        "alias": "Google AI",
        "name": "Google AI Studio",
        "icon": "auto_awesome",
        "color": "#4285F4",
        "textIcon": "GO",
        "website": "https://ai.google.dev",
        "hasFree": True,
        "freeNote": "Ücretsiz Gemini API erişimi (kota dahil)",
        "serviceKinds": ["chat", "completion", "embedding", "image", "code"],
    },
    "gemini": {
        "id": "gemini",
        "alias": "Gemini",
        "name": "Google Gemini",
        "icon": "auto_awesome",
        "color": "#1A73E8",
        "textIcon": "GE",
        "website": "https://gemini.google.com",
        "hasFree": True,
        "freeNote": "Ücretsiz katman mevcut",
        "serviceKinds": ["chat", "completion", "embedding", "image", "code"],
    },
    "deepseek": {
        "id": "deepseek",
        "alias": "DeepSeek",
        "name": "DeepSeek",
        "icon": "water_drop",
        "color": "#4D6BFE",
        "textIcon": "DS",
        "website": "https://deepseek.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi var",
        "serviceKinds": ["chat", "completion", "code"],
    },
    "mistral": {
        "id": "mistral",
        "alias": "Mistral",
        "name": "Mistral AI",
        "icon": "air",
        "color": "#F7A046",
        "textIcon": "MI",
        "website": "https://mistral.ai",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok; düşük fiyatlı",
        "serviceKinds": ["chat", "completion", "embedding", "code"],
    },
    "xai": {
        "id": "xai",
        "alias": "xAI",
        "name": "xAI (Grok)",
        "icon": "bolt",
        "color": "#1D9BF0",
        "textIcon": "xA",
        "website": "https://x.ai",
        "hasFree": False,
        "freeNote": "API erişimi ücretli",
        "serviceKinds": ["chat", "completion", "code"],
    },
    "meta-llama": {
        "id": "meta-llama",
        "alias": "Meta Llama",
        "name": "Meta Llama",
        "icon": "pets",
        "color": "#0668E1",
        "textIcon": "LL",
        "website": "https://llama.meta.com",
        "hasFree": True,
        "freeNote": "Açık kaynak modeller ücretsiz",
        "serviceKinds": ["chat", "completion", "code"],
    },
    "cohere": {
        "id": "cohere",
        "alias": "Cohere",
        "name": "Cohere",
        "icon": "hub",
        "color": "#39594D",
        "textIcon": "CO",
        "website": "https://cohere.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme planı mevcut",
        "serviceKinds": ["chat", "completion", "embedding", "rerank", "code"],
    },
    "perplexity": {
        "id": "perplexity",
        "alias": "Perplexity",
        "name": "Perplexity AI",
        "icon": "search",
        "color": "#1FB8CD",
        "textIcon": "PX",
        "website": "https://perplexity.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz arama-sorgu katmanı",
        "serviceKinds": ["chat", "search", "completion"],
    },
    "reka": {
        "id": "reka",
        "alias": "Reka",
        "name": "Reka AI",
        "icon": "auto_graph",
        "color": "#7C3AED",
        "textIcon": "RK",
        "website": "https://reka.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["chat", "completion", "image"],
    },

    # ════════════════════════════════════════════════════════════════════════
    #  ÇIKARIM / ALTYAPI SAĞLAYICILARI  (Inference)
    # ════════════════════════════════════════════════════════════════════════
    "together": {
        "id": "together",
        "alias": "Together AI",
        "name": "Together AI",
        "icon": "groups",
        "color": "#6366F1",
        "textIcon": "TG",
        "website": "https://together.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi ($25)",
        "serviceKinds": ["chat", "completion", "embedding", "code"],
    },
    "groq": {
        "id": "groq",
        "alias": "Groq",
        "name": "Groq",
        "icon": "bolt",
        "color": "#F55036",
        "textIcon": "GQ",
        "website": "https://groq.com",
        "hasFree": True,
        "freeNote": "Ücretsiz katman mevcut (hız odaklı)",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "fireworks": {
        "id": "fireworks",
        "alias": "Fireworks AI",
        "name": "Fireworks AI",
        "icon": "local_fire_department",
        "color": "#FF6B35",
        "textIcon": "FW",
        "website": "https://fireworks.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "cerebras": {
        "id": "cerebras",
        "alias": "Cerebras",
        "name": "Cerebras",
        "icon": "memory",
        "color": "#00B4D8",
        "textIcon": "CB",
        "website": "https://cerebras.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme katmanı",
        "serviceKinds": ["chat", "completion"],
    },
    "nvidia": {
        "id": "nvidia",
        "alias": "NVIDIA NIM",
        "name": "NVIDIA NIM",
        "icon": "developer_board",
        "color": "#76B900",
        "textIcon": "NV",
        "website": "https://build.nvidia.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "nebius": {
        "id": "nebius",
        "alias": "Nebius AI",
        "name": "Nebius AI Studio",
        "icon": "cloud",
        "color": "#7C3AED",
        "textIcon": "NB",
        "website": "https://nebius.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi ($50)",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "deepinfra": {
        "id": "deepinfra",
        "alias": "DeepInfra",
        "name": "DeepInfra",
        "icon": "dns",
        "color": "#8B5CF6",
        "textIcon": "DI",
        "website": "https://deepinfra.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "sambanova": {
        "id": "sambanova",
        "alias": "SambaNova",
        "name": "SambaNova Cloud",
        "icon": "cloud_queue",
        "color": "#E11D48",
        "textIcon": "SN",
        "website": "https://cloud.sambanova.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme katmanı",
        "serviceKinds": ["chat", "completion"],
    },
    "lambda-ai": {
        "id": "lambda-ai",
        "alias": "Lambda",
        "name": "Lambda Cloud",
        "icon": "functions",
        "color": "#6366F1",
        "textIcon": "LM",
        "website": "https://lambdalabs.com",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok; GPU bulut hizmeti",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "huggingface": {
        "id": "huggingface",
        "alias": "HuggingFace",
        "name": "HuggingFace Inference",
        "icon": "sentiment_satisfied",
        "color": "#FFD21E",
        "textIcon": "HF",
        "website": "https://huggingface.co",
        "hasFree": True,
        "freeNote": "Ücretsiz API erişimi (kota dahil)",
        "serviceKinds": ["chat", "completion", "embedding", "image", "code"],
    },
    "replicate": {
        "id": "replicate",
        "alias": "Replicate",
        "name": "Replicate",
        "icon": "content_copy",
        "color": "#3B82F6",
        "textIcon": "RE",
        "website": "https://replicate.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi ($5)",
        "serviceKinds": ["chat", "completion", "image", "video", "audio"],
    },
    "siliconflow": {
        "id": "siliconflow",
        "alias": "SiliconFlow",
        "name": "SiliconFlow",
        "icon": "water",
        "color": "#0EA5E9",
        "textIcon": "SF",
        "website": "https://siliconflow.cn",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "hyperbolic": {
        "id": "hyperbolic",
        "alias": "Hyperbolic",
        "name": "Hyperbolic Labs",
        "icon": "speed",
        "color": "#A855F7",
        "textIcon": "HB",
        "website": "https://hyperbolic.xyz",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "baseten": {
        "id": "baseten",
        "alias": "Baseten",
        "name": "Baseten",
        "icon": "view_in_ar",
        "color": "#0EA5E9",
        "textIcon": "BT",
        "website": "https://baseten.co",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion"],
    },
    "featherless-ai": {
        "id": "featherless-ai",
        "alias": "Featherless",
        "name": "Featherless AI",
        "icon": "filter_drama",
        "color": "#94A3B8",
        "textIcon": "FL",
        "website": "https://featherless.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["chat", "completion"],
    },

    # ════════════════════════════════════════════════════════════════════════
    #  GÖRSEL / ÖZEL SAĞLAYICILAR  (Specialty)
    # ════════════════════════════════════════════════════════════════════════
    "stability-ai": {
        "id": "stability-ai",
        "alias": "Stability AI",
        "name": "Stability AI",
        "icon": "blur_on",
        "color": "#A855F7",
        "textIcon": "SA",
        "website": "https://stability.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi ($10)",
        "serviceKinds": ["image", "video", "audio"],
    },
    "black-forest-labs": {
        "id": "black-forest-labs",
        "alias": "Black Forest Labs",
        "name": "Black Forest Labs (FLUX)",
        "icon": "forest",
        "color": "#059669",
        "textIcon": "BF",
        "website": "https://blackforestlabs.ai",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok",
        "serviceKinds": ["image"],
    },
    "fal-ai": {
        "id": "fal-ai",
        "alias": "FAL.ai",
        "name": "FAL.ai",
        "icon": "flash_on",
        "color": "#F59E0B",
        "textIcon": "FA",
        "website": "https://fal.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi ($5)",
        "serviceKinds": ["image", "video", "audio"],
    },
    "ideogram": {
        "id": "ideogram",
        "alias": "Ideogram",
        "name": "Ideogram",
        "icon": "text_fields",
        "color": "#7C3AED",
        "textIcon": "ID",
        "website": "https://ideogram.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["image"],
    },
    "leonardo": {
        "id": "leonardo",
        "alias": "Leonardo AI",
        "name": "Leonardo AI",
        "icon": "palette",
        "color": "#8B5CF6",
        "textIcon": "LA",
        "website": "https://leonardo.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz 150 jeton/gün",
        "serviceKinds": ["image", "video"],
    },
    "recraft": {
        "id": "recraft",
        "alias": "Recraft",
        "name": "Recraft",
        "icon": "brush",
        "color": "#111827",
        "textIcon": "RC",
        "website": "https://recraft.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["image"],
    },
    "runwayml": {
        "id": "runwayml",
        "alias": "Runway",
        "name": "Runway",
        "icon": "videocam",
        "color": "#EF4444",
        "textIcon": "RW",
        "website": "https://runwayml.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["video", "image"],
    },
    "haiper": {
        "id": "haiper",
        "alias": "Haiper",
        "name": "Haiper AI",
        "icon": "movie",
        "color": "#EC4899",
        "textIcon": "HP",
        "website": "https://haiper.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme",
        "serviceKinds": ["video", "image"],
    },
    "suno": {
        "id": "suno",
        "alias": "Suno",
        "name": "Suno AI",
        "icon": "music_note",
        "color": "#10B981",
        "textIcon": "SN",
        "website": "https://suno.com",
        "hasFree": True,
        "freeNote": "Ücretsiz 10 şarkı/gün",
        "serviceKinds": ["audio"],
    },
    "udio": {
        "id": "udio",
        "alias": "Udio",
        "name": "Udio",
        "icon": "queue_music",
        "color": "#6366F1",
        "textIcon": "UD",
        "website": "https://udio.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["audio"],
    },

    # ════════════════════════════════════════════════════════════════════════
    #  SES / EMBEDDING SAĞLAYICILARI  (Audio & Embedding)
    # ════════════════════════════════════════════════════════════════════════
    "elevenlabs": {
        "id": "elevenlabs",
        "alias": "ElevenLabs",
        "name": "ElevenLabs",
        "icon": "record_voice_over",
        "color": "#22C55E",
        "textIcon": "EL",
        "website": "https://elevenlabs.io",
        "hasFree": True,
        "freeNote": "Ücretsiz 10.000 karakter/ay",
        "serviceKinds": ["tts", "stt", "audio"],
    },
    "deepgram": {
        "id": "deepgram",
        "alias": "Deepgram",
        "name": "Deepgram",
        "icon": "graphic_eq",
        "color": "#7C3AED",
        "textIcon": "DG",
        "website": "https://deepgram.com",
        "hasFree": True,
        "freeNote": "Ücretsiz $200 kredi",
        "serviceKinds": ["stt", "audio"],
    },
    "assemblyai": {
        "id": "assemblyai",
        "alias": "AssemblyAI",
        "name": "AssemblyAI",
        "icon": "mic",
        "color": "#EF4444",
        "textIcon": "AA",
        "website": "https://assemblyai.com",
        "hasFree": True,
        "freeNote": "Ücretsiz $100 kredi",
        "serviceKinds": ["stt", "audio"],
    },
    "cartesia": {
        "id": "cartesia",
        "alias": "Cartesia",
        "name": "Cartesia AI",
        "icon": "volume_up",
        "color": "#1E40AF",
        "textIcon": "CA",
        "website": "https://cartesia.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["tts", "audio"],
    },
    "playht": {
        "id": "playht",
        "alias": "PlayHT",
        "name": "PlayHT",
        "icon": "campaign",
        "color": "#059669",
        "textIcon": "PH",
        "website": "https://play.ht",
        "hasFree": True,
        "freeNote": "Ücretsiz 12.500 karakter/ay",
        "serviceKinds": ["tts", "audio"],
    },
    "voyage-ai": {
        "id": "voyage-ai",
        "alias": "Voyage AI",
        "name": "Voyage AI",
        "icon": "explore",
        "color": "#2563EB",
        "textIcon": "VA",
        "website": "https://voyageai.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["embedding", "rerank"],
    },
    "jina-ai": {
        "id": "jina-ai",
        "alias": "Jina AI",
        "name": "Jina AI",
        "icon": "api",
        "color": "#F97316",
        "textIcon": "JA",
        "website": "https://jina.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["embedding", "rerank", "chat"],
    },
    "nomic": {
        "id": "nomic",
        "alias": "Nomic AI",
        "name": "Nomic AI",
        "icon": "scatter_plot",
        "color": "#8B5CF6",
        "textIcon": "NM",
        "website": "https://nomic.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz API erişimi",
        "serviceKinds": ["embedding"],
    },
    "mixedbread": {
        "id": "mixedbread",
        "alias": "Mixedbread",
        "name": "Mixedbread AI",
        "icon": "grain",
        "color": "#10B981",
        "textIcon": "MB",
        "website": "https://mixedbread.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["embedding", "rerank"],
    },

    # ════════════════════════════════════════════════════════════════════════
    #  KURUMSAL SAĞLAYICILAR  (Enterprise)
    # ════════════════════════════════════════════════════════════════════════
    "azure-openai": {
        "id": "azure-openai",
        "alias": "Azure OpenAI",
        "name": "Azure OpenAI Service",
        "icon": "cloud",
        "color": "#0078D4",
        "textIcon": "AZ",
        "website": "https://azure.microsoft.com/ai",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok; kurumsal lisans",
        "serviceKinds": ["chat", "completion", "embedding", "image", "code"],
    },
    "bedrock": {
        "id": "bedrock",
        "alias": "AWS Bedrock",
        "name": "Amazon Bedrock",
        "icon": "cloud",
        "color": "#FF9900",
        "textIcon": "BR",
        "website": "https://aws.amazon.com/bedrock",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok; AWS lisansı",
        "serviceKinds": ["chat", "completion", "embedding", "image", "code"],
    },
    "vertex": {
        "id": "vertex",
        "alias": "Vertex AI",
        "name": "Google Vertex AI",
        "icon": "cloud",
        "color": "#4285F4",
        "textIcon": "VA",
        "website": "https://cloud.google.com/vertex-ai",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok; GCP lisansı",
        "serviceKinds": ["chat", "completion", "embedding", "image", "code"],
    },
    "cloudflare-ai": {
        "id": "cloudflare-ai",
        "alias": "Cloudflare AI",
        "name": "Cloudflare Workers AI",
        "icon": "cloud",
        "color": "#F48120",
        "textIcon": "CF",
        "website": "https://developers.cloudflare.com/workers-ai",
        "hasFree": True,
        "freeNote": "Ücretsiz 10.000 neuron/gün",
        "serviceKinds": ["chat", "completion", "embedding", "image"],
    },
    "databricks": {
        "id": "databricks",
        "alias": "Databricks",
        "name": "Databricks Mosaic AI",
        "icon": "account_tree",
        "color": "#FF3621",
        "textIcon": "DB",
        "website": "https://databricks.com/product/mosaic-ai",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok; kurumsal",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "snowflake": {
        "id": "snowflake",
        "alias": "Snowflake",
        "name": "Snowflake Cortex AI",
        "icon": "ac_unit",
        "color": "#29B5E8",
        "textIcon": "SF",
        "website": "https://snowflake.com",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok; kurumsal",
        "serviceKinds": ["chat", "completion"],
    },
    "scaleway": {
        "id": "scaleway",
        "alias": "Scaleway",
        "name": "Scaleway",
        "icon": "scale",
        "color": "#0052FF",
        "textIcon": "SC",
        "website": "https://scaleway.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion"],
    },

    # ════════════════════════════════════════════════════════════════════════
    #  GEÇİT SAĞLAYICILARI  (Gateways)
    # ════════════════════════════════════════════════════════════════════════
    "openrouter": {
        "id": "openrouter",
        "alias": "OpenRouter",
        "name": "OpenRouter",
        "icon": "route",
        "color": "#8B5CF6",
        "textIcon": "OR",
        "website": "https://openrouter.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz modeller mevcut",
        "serviceKinds": ["chat", "completion", "embedding", "image", "code"],
    },
    "novita": {
        "id": "novita",
        "alias": "Novita AI",
        "name": "Novita AI",
        "icon": "rocket_launch",
        "color": "#7C3AED",
        "textIcon": "NV",
        "website": "https://novita.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion"],
    },
    "chutes": {
        "id": "chutes",
        "alias": "Chutes AI",
        "name": "Chutes AI",
        "icon": "bolt",
        "color": "#22C55E",
        "textIcon": "CH",
        "website": "https://chutes.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["chat", "completion"],
    },
    "aimlapi": {
        "id": "aimlapi",
        "alias": "AIML API",
        "name": "AIML API",
        "icon": "api",
        "color": "#EC4899",
        "textIcon": "AM",
        "website": "https://aimlapi.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi ($1)",
        "serviceKinds": ["chat", "completion", "image", "audio"],
    },
    "poe": {
        "id": "poe",
        "alias": "Poe",
        "name": "Poe by Quora",
        "icon": "chat",
        "color": "#A855F7",
        "textIcon": "PO",
        "website": "https://poe.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion", "image"],
    },

    # ════════════════════════════════════════════════════════════════════════
    #  BÖLGESEL SAĞLAYICILAR  (Regional / Türkiye-Dostu)
    # ════════════════════════════════════════════════════════════════════════
    "minimax": {
        "id": "minimax",
        "alias": "MiniMax",
        "name": "MiniMax",
        "icon": "tune",
        "color": "#3B82F6",
        "textIcon": "MM",
        "website": "https://minimaxi.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion", "tts", "audio"],
    },
    "kimi": {
        "id": "kimi",
        "alias": "Kimi",
        "name": "Moonshot Kimi",
        "icon": "emoji_objects",
        "color": "#0EA5E9",
        "textIcon": "KI",
        "website": "https://kimi.moonshot.cn",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme",
        "serviceKinds": ["chat", "completion"],
    },
    "qianfan": {
        "id": "qianfan",
        "alias": "Qianfan",
        "name": "Baidu Qianfan",
        "icon": "translate",
        "color": "#2932E1",
        "textIcon": "QF",
        "website": "https://qianfan.baidubce.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion", "embedding", "image"],
    },
    "alibaba": {
        "id": "alibaba",
        "alias": "Alibaba",
        "name": "Alibaba Tongyi",
        "icon": "storefront",
        "color": "#FF6A00",
        "textIcon": "AL",
        "website": "https://tongyi.aliyun.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme",
        "serviceKinds": ["chat", "completion", "embedding", "image"],
    },
    "gigachat": {
        "id": "gigachat",
        "alias": "GigaChat",
        "name": "Sber GigaChat",
        "icon": "forum",
        "color": "#1B5E20",
        "textIcon": "GC",
        "website": "https://developers.sber.ru/gigachat",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["chat", "completion"],
    },

    # ════════════════════════════════════════════════════════════════════════
    #  ARAÇ / UYGULAMA SAĞLAYICILARI  (Tools & Apps)
    # ════════════════════════════════════════════════════════════════════════
    "firecrawl": {
        "id": "firecrawl",
        "alias": "Firecrawl",
        "name": "Firecrawl",
        "icon": "travel_explore",
        "color": "#E11D48",
        "textIcon": "FC",
        "website": "https://firecrawl.dev",
        "hasFree": True,
        "freeNote": "Ücretsiz 500 sayfa/ay",
        "serviceKinds": ["search"],
    },
    "serper": {
        "id": "serper",
        "alias": "Serper",
        "name": "Serper",
        "icon": "search",
        "color": "#22C55E",
        "textIcon": "SP",
        "website": "https://serper.dev",
        "hasFree": True,
        "freeNote": "Ücretsiz 2.500 sorgu",
        "serviceKinds": ["search"],
    },
    "brave-search": {
        "id": "brave-search",
        "alias": "Brave Search",
        "name": "Brave Search API",
        "icon": "search",
        "color": "#FB542B",
        "textIcon": "BS",
        "website": "https://brave.com/search/api",
        "hasFree": True,
        "freeNote": "Ücretsiz 2.000 sorgu/ay",
        "serviceKinds": ["search"],
    },
    "exa": {
        "id": "exa",
        "alias": "Exa",
        "name": "Exa Search",
        "icon": "travel_explore",
        "color": "#6366F1",
        "textIcon": "EX",
        "website": "https://exa.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz 1.000 sorgu/ay",
        "serviceKinds": ["search", "embedding"],
    },
    "tavily": {
        "id": "tavily",
        "alias": "Tavily",
        "name": "Tavily Search",
        "icon": "search",
        "color": "#0EA5E9",
        "textIcon": "TV",
        "website": "https://tavily.com",
        "hasFree": True,
        "freeNote": "Ücretsiz 1.000 sorgu/ay",
        "serviceKinds": ["search"],
    },
    "dify": {
        "id": "dify",
        "alias": "Dify",
        "name": "Dify",
        "icon": "extension",
        "color": "#4F46E5",
        "textIcon": "DF",
        "website": "https://dify.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz 200 mesaj/ay",
        "serviceKinds": ["chat", "completion"],
    },
    "nlpcloud": {
        "id": "nlpcloud",
        "alias": "NLPCloud",
        "name": "NLPCloud",
        "icon": "text_snippet",
        "color": "#0EA5E9",
        "textIcon": "NC",
        "website": "https://nlpcloud.com",
        "hasFree": True,
        "freeNote": "Ücretsiz katman mevcut",
        "serviceKinds": ["chat", "completion", "embedding"],
    },

    # ════════════════════════════════════════════════════════════════════════
    #  YEREL SAĞLAYICILAR  (Local / Self-hosted)
    # ════════════════════════════════════════════════════════════════════════
    "ollama": {
        "id": "ollama",
        "alias": "Ollama",
        "name": "Ollama (Yerel)",
        "icon": "computer",
        "color": "#FFFFFF",
        "textIcon": "OL",
        "website": "https://ollama.com",
        "hasFree": True,
        "freeNote": "Tamamen ücretsiz ve açık kaynak",
        "serviceKinds": ["chat", "completion", "embedding", "code"],
    },
    "llamafile": {
        "id": "llamafile",
        "alias": "Llamafile",
        "name": "Llamafile",
        "icon": "folder_special",
        "color": "#F59E0B",
        "textIcon": "LF",
        "website": "https://github.com/Mozilla-Ocho/llamafile",
        "hasFree": True,
        "freeNote": "Tamamen ücretsiz ve açık kaynak",
        "serviceKinds": ["chat", "completion"],
    },
    "lm-studio": {
        "id": "lm-studio",
        "alias": "LM Studio",
        "name": "LM Studio",
        "icon": "desktop_windows",
        "color": "#6366F1",
        "textIcon": "LS",
        "website": "https://lmstudio.ai",
        "hasFree": True,
        "freeNote": "Tamamen ücretsiz",
        "serviceKinds": ["chat", "completion", "embedding"],
    },

    # ════════════════════════════════════════════════════════════════════════
    #  EK SAĞLAYICILAR  (Additional)
    # ════════════════════════════════════════════════════════════════════════
    "ai21": {
        "id": "ai21",
        "alias": "AI21 Labs",
        "name": "AI21 Labs",
        "icon": "science",
        "color": "#1E40AF",
        "textIcon": "A1",
        "website": "https://ai21.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion"],
    },
    "upstage": {
        "id": "upstage",
        "alias": "Upstage",
        "name": "Upstage AI",
        "icon": "trending_up",
        "color": "#22C55E",
        "textIcon": "UP",
        "website": "https://upstage.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion", "embedding"],
    },
    "codestral": {
        "id": "codestral",
        "alias": "Codestral",
        "name": "Mistral Codestral",
        "icon": "code",
        "color": "#F7A046",
        "textIcon": "CS",
        "website": "https://mistral.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["code", "chat", "completion"],
    },
    "venice": {
        "id": "venice",
        "alias": "Venice",
        "name": "Venice AI",
        "icon": "mask",
        "color": "#0EA5E9",
        "textIcon": "VC",
        "website": "https://venice.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["chat", "completion", "image"],
    },
    "nous-research": {
        "id": "nous-research",
        "alias": "Nous Research",
        "name": "Nous Research",
        "icon": "psychology_alt",
        "color": "#10B981",
        "textIcon": "NR",
        "website": "https://nousresearch.com",
        "hasFree": False,
        "freeNote": "API erişimi ücretli",
        "serviceKinds": ["chat", "completion"],
    },
    "arcee-ai": {
        "id": "arcee-ai",
        "alias": "Arcee AI",
        "name": "Arcee AI",
        "icon": "school",
        "color": "#7C3AED",
        "textIcon": "AR",
        "website": "https://arcee.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion"],
    },
    "liquid": {
        "id": "liquid",
        "alias": "Liquid AI",
        "name": "Liquid AI",
        "icon": "water_drop",
        "color": "#06B6D4",
        "textIcon": "LQ",
        "website": "https://liquid.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["chat", "completion"],
    },
    "maritalk": {
        "id": "maritalk",
        "alias": "MariTalk",
        "name": "MariTalk (Kbled)",
        "icon": "chat_bubble",
        "color": "#10B981",
        "textIcon": "MT",
        "website": "https://maritaca.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion"],
    },
    "blackbox": {
        "id": "blackbox",
        "alias": "Blackbox",
        "name": "Blackbox AI",
        "icon": "developer_mode",
        "color": "#000000",
        "textIcon": "BB",
        "website": "https://blackbox.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz katman mevcut",
        "serviceKinds": ["chat", "completion", "code"],
    },
    "galadriel": {
        "id": "galadriel",
        "alias": "Galadriel",
        "name": "Galadriel AI",
        "icon": "auto_awesome",
        "color": "#7C3AED",
        "textIcon": "GA",
        "website": "https://galadriel.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["chat", "completion"],
    },
    "morph": {
        "id": "morph",
        "alias": "Morph",
        "name": "Morph AI",
        "icon": "transform",
        "color": "#8B5CF6",
        "textIcon": "MP",
        "website": "https://morphllm.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["chat", "completion"],
    },
    "pioneer": {
        "id": "pioneer",
        "alias": "Pioneer",
        "name": "Pioneer AI",
        "icon": "explore",
        "color": "#F59E0B",
        "textIcon": "PG",
        "website": "https://pioneer.ai",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme mevcut",
        "serviceKinds": ["chat", "completion"],
    },
    "digitalocean": {
        "id": "digitalocean",
        "alias": "DigitalOcean",
        "name": "DigitalOcean AI",
        "icon": "cloud",
        "color": "#0080FF",
        "textIcon": "DO",
        "website": "https://www.digitalocean.com",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["chat", "completion"],
    },
    "pollinations": {
        "id": "pollinations",
        "alias": "Pollinations",
        "name": "Pollinations AI",
        "icon": "grass",
        "color": "#22C55E",
        "textIcon": "PO",
        "website": "https://pollinations.ai",
        "hasFree": True,
        "freeNote": "Tamamen ücretsiz",
        "serviceKinds": ["image", "chat", "completion"],
    },
    "topaz": {
        "id": "topaz",
        "alias": "Topaz Labs",
        "name": "Topaz Labs",
        "icon": "photo_camera",
        "color": "#1E40AF",
        "textIcon": "TZ",
        "website": "https://topazlabs.com",
        "hasFree": False,
        "freeNote": "Ücretsiz plan yok; masaüstü yazılım",
        "serviceKinds": ["image"],
    },
    "segmind": {
        "id": "segmind",
        "alias": "Segmind",
        "name": "Segmind",
        "icon": "tune",
        "color": "#7C3AED",
        "textIcon": "SG",
        "website": "https://segmind.com",
        "hasFree": True,
        "freeNote": "Ücretsiz 100 istek/gün",
        "serviceKinds": ["image", "video"],
    },
    "v0-vercel": {
        "id": "v0-vercel",
        "alias": "v0",
        "name": "v0 by Vercel",
        "icon": "code",
        "color": "#000000",
        "textIcon": "v0",
        "website": "https://v0.dev",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme kredisi",
        "serviceKinds": ["code", "chat"],
    },
    "gitlab": {
        "id": "gitlab",
        "alias": "GitLab Duo",
        "name": "GitLab Duo",
        "icon": "commit",
        "color": "#FC6D26",
        "textIcon": "GL",
        "website": "https://about.gitlab.com/duo",
        "hasFree": True,
        "freeNote": "Ücretsiz deneme 30 gün",
        "serviceKinds": ["code", "chat"],
    },
}


# ── Helper Functions ────────────────────────────────────────────────────────

def get_provider_by_id(provider_id: str) -> Optional[Dict]:
    """
    ID ile provider bilgisi getir.
    
    Args:
        provider_id: Provider tanımlayıcısı (ör: "openai", "anthropic")
    
    Returns:
        Provider dict veya None
    """
    return PROVIDER_CATALOG.get(provider_id)


def list_providers_from_catalog(
    service_kind: Optional[str] = None,
    free_only: bool = False,
    category: Optional[str] = None,
) -> List[Dict]:
    """
    Katalogdan provider listesi getir.
    
    Args:
        service_kind: Sadece belirli servis türünü içeren provider'lar
        free_only: Sadece ücretsiz planı olan provider'lar
        category: Kategorisine göre filtrele (service_kind içinde)
    
    Returns:
        Provider dict listesi
    """
    results = []
    for pid, pdata in PROVIDER_CATALOG.items():
        if free_only and not pdata.get("hasFree", False):
            continue
        if service_kind and service_kind not in pdata.get("serviceKinds", []):
            continue
        results.append(pdata)
    return results


def get_providers_by_service_kind(service_kind: str) -> List[Dict]:
    """Belirli bir servis türünü sunan tüm provider'ları getir."""
    return list_providers_from_catalog(service_kind=service_kind)


def get_free_providers() -> List[Dict]:
    """Ücretsiz planı olan tüm provider'ları getir."""
    return list_providers_from_catalog(free_only=True)


def get_all_service_kinds() -> List[str]:
    """Katalogdaki tüm benzersiz servis türlerini listele."""
    kinds = set()
    for pdata in PROVIDER_CATALOG.values():
        kinds.update(pdata.get("serviceKinds", []))
    return sorted(kinds)


def get_catalog_stats() -> Dict:
    """Katalog istatistiklerini getir."""
    total = len(PROVIDER_CATALOG)
    free_count = sum(1 for p in PROVIDER_CATALOG.values() if p.get("hasFree"))
    kinds_count = len(get_all_service_kinds())
    kind_distribution = {}
    for pdata in PROVIDER_CATALOG.values():
        for kind in pdata.get("serviceKinds", []):
            kind_distribution[kind] = kind_distribution.get(kind, 0) + 1
    
    return {
        "total_providers": total,
        "free_providers": free_count,
        "paid_providers": total - free_count,
        "service_kinds_count": kinds_count,
        "service_kind_distribution": kind_distribution,
    }


# ── Module Export ───────────────────────────────────────────────────────────
__all__ = [
    "PROVIDER_CATALOG",
    "get_provider_by_id",
    "list_providers_from_catalog",
    "get_providers_by_service_kind",
    "get_free_providers",
    "get_all_service_kinds",
    "get_catalog_stats",
]


if __name__ == "__main__":
    # Modül olarak çalıştırıldığında istatistikleri göster
    stats = get_catalog_stats()
    print(f"📊 Köprü Provider Kataloğu")
    print(f"   Toplam provider: {stats['total_providers']}")
    print(f"   Ücretsiz: {stats['free_providers']}")
    print(f"   Ücretli: {stats['paid_providers']}")
    print(f"   Servis türü: {stats['service_kinds_count']}")
    print()
    print("🔧 Servis Dağılımı:")
    for kind, count in sorted(stats["service_kind_distribution"].items(), 
                              key=lambda x: -x[1]):
        print(f"   {kind}: {count} provider")
